apiVersion: v1
kind: Namespace
metadata:
  name: spiderman

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spiderman
  namespace: spiderman
subjects:
- kind: User
  name: spiderman
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
